USE [mssql_php]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TestTable](
	[TT_ID] [int] IDENTITY(1,1) NOT NULL,
	[TT_Name] [text] NULL,
	[TT_Date] [date] NULL,
	[TT_Amount] [numeric](18, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[TT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO